controller_list:
  - name: fake_Left_Arm_controller
    joints:
      - l_sho_pitch
      - l_sho_roll
      - l_el
  - name: fake_Right_Arm_controller
    joints:
      - r_sho_pitch
      - r_sho_roll
      - r_el
  - name: fake_Left_Leg_controller
    joints:
      - l_hip_yaw
      - l_hip_roll
      - l_hip_pitch
      - l_knee
      - l_ank_pitch
      - l_ank_roll
  - name: fake_Right_Leg_controller
    joints:
      - r_hip_yaw
      - r_hip_roll
      - r_hip_pitch
      - r_knee
      - r_ank_pitch
      - r_ank_roll
  - name: fake_Head_controller
    joints:
      - head_pan
      - head_tilt
initial:  # Define initial robot poses.
  - group: Left_Arm
    pose: home_position
  - group: Right_Arm
    pose: home_position
  - group: Left_Leg
    pose: home_position
  - group: Right_Leg
    pose: home_position
  - group: Head
    pose: home_position